# Server settings
server.port=${PORT:8080}

# Database (Render & local)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/facebook_db?sslmode=disable}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Enable detailed logging for debugging (optional)
logging.level.org.springframework.web=INFO
logging.level.com.musngi.facebookapi=DEBUG
